
#define SUITE(...) UNIT_SUITE(__VA_ARGS__)
#define DESCRIBE(...) UNIT_DESCRIBE(__VA_ARGS__)
#define IT(...) UNIT_TEST(__VA_ARGS__)
#define TEST(...) UNIT_TEST(__VA_ARGS__)
#define ECHO(...) UNIT_ECHO(__VA_ARGS__)

#define WARN(...)       UNIT_WARN(__VA_ARGS__)
#define WARN_FALSE(...) UNIT_WARN_FALSE(__VA_ARGS__)
#define WARN_EQ(...)    UNIT_WARN_EQ(__VA_ARGS__)
#define WARN_NE(...)    UNIT_WARN_NE(__VA_ARGS__)
#define WARN_GT(...)    UNIT_WARN_GT(__VA_ARGS__)
#define WARN_GE(...)    UNIT_WARN_GE(__VA_ARGS__)
#define WARN_LT(...)    UNIT_WARN_LT(__VA_ARGS__)
#define WARN_LE(...)    UNIT_WARN_LE(__VA_ARGS__)

#define CHECK(...)       UNIT_CHECK(__VA_ARGS__)
#define CHECK_FALSE(...) UNIT_CHECK_FALSE(__VA_ARGS__)
#define CHECK_EQ(...)    UNIT_CHECK_EQ(__VA_ARGS__)
#define CHECK_NE(...)    UNIT_CHECK_NE(__VA_ARGS__)
#define CHECK_GT(...)    UNIT_CHECK_GT(__VA_ARGS__)
#define CHECK_GE(...)    UNIT_CHECK_GE(__VA_ARGS__)
#define CHECK_LT(...)    UNIT_CHECK_LT(__VA_ARGS__)
#define CHECK_LE(...)    UNIT_CHECK_LE(__VA_ARGS__)

#define REQUIRE(...)       UNIT_REQUIRE(__VA_ARGS__)
#define REQUIRE_FALSE(...) UNIT_REQUIRE_FALSE(__VA_ARGS__)
#define REQUIRE_EQ(...)    UNIT_REQUIRE_EQ(__VA_ARGS__)
#define REQUIRE_NE(...)    UNIT_REQUIRE_NE(__VA_ARGS__)
#define REQUIRE_GT(...)    UNIT_REQUIRE_GT(__VA_ARGS__)
#define REQUIRE_GE(...)    UNIT_REQUIRE_GE(__VA_ARGS__)
#define REQUIRE_LT(...)    UNIT_REQUIRE_LT(__VA_ARGS__)
#define REQUIRE_LE(...)    UNIT_REQUIRE_LE(__VA_ARGS__)

#define SKIP(...) UNIT_SKIP(__VA_ARGS__)
